### ISSUE TITLE
c:\Program Files\Git\usr\bin\ is hardcoded.

### ISSUE THREAD

**Issue by kotenok2000** [loda-lang/loda-cpp#144]
It can't find gzip.
I have git installed in E:\Program Files\Git\

**Comment by ckrause** [comment]
The problem is that BOINC removes all environment variables before starting our app, including `PATH`. We have no way of inferring the actual location of `git`.

**Comment by ckrause** [comment]
I think the problem is here:
https://github.com/BOINC/boinc/blob/master/samples/wrapper/wrapper.cpp#L820
If I understand it correctly, it does NOT inherit the environment variables from the parent process.

**Comment by kotenok2000** [comment]
Can git and curl be bundled with boinc project?

**Comment by ckrause** [comment]
That would be nice. I don't know though if the have runtime dependencies. For example, git comes with lots of tools when you install it.

**Comment by ckrause** [comment]
On Windows, we now bundle MinGit and gzip with the boinc app. No need for manual installation anymore.
