### ISSUE TITLE
Language spec: Disallow zero prefixes in parameter values

### ISSUE THREAD

**Issue by neoneye** [loda-lang/loda-cpp#176]
Examples: 
```asm
mul $00,-01
cmp $007,-007
```

A fun case is the value `-000` which is both negative and has leading zeroes.

**Comment by ckrause** [comment]
Does this need to be fixed only in the language spec or also in loda-cpp?
Change requests to the language spec should go here: https://github.com/loda-lang/loda-lang.github.io/issues

**Comment by neoneye** [comment]
IMO the primarily the code should disallow it.

And secondarily maybe write it in the language spec.

**Comment by ckrause** [comment]
Fixed
