### ISSUE TITLE
Instruction "zap" for removal of a divisor

### ISSUE THREAD

**Issue by neoneye** [loda-lang/loda-cpp#182]
In order to prevent huge magic constants. 

In [A086761](https://loda-lang.org/edit/?oeis=86761) there is a huge constant, it looks like this:
```asm
mov $1,100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
It's used for doing a `gcd`. Accomplishing the same as A132740.
Since it's a `gcd`, it's very cheap to do.
Unlike A132740 that uses loops and is expensive.

The [A132740](https://loda-lang.org/edit/?oeis=A132740) looks like this:

```asm
add $0,1
lpb $0
  dif $0,2
lpe
lpb $0
  dif $0,5
lpe
```

The above code can be simplified to this:

```asm
add $0,1
zap $0,2
zap $0,5
```

This way large constants may be prevented.

Doing `zap` with non-prime values, then it behaves as it was a `lpb dif lpe` loop.

Doing `zap` with a negative value, then it alternates between plus/minus, the same way as the `lpb dif lpe` loop.

**Comment by ckrause** [comment]
Nice idea, I like the name :). It would be interesting to know how many programs have this simple `dif` loop and could be converted directly. One disadvantage might be that you can't count the number of `dif` executions (= exponent in prime factorization) anymore. Also I'm not sure if this will prevent the miner from generating such huge constants. We do have some refactoring logic in the minimizer already that replaces `gcd` with large constants by a `dif` loop: https://github.com/loda-lang/loda-cpp/blob/main/src/minimizer.cpp#L96-L112

**Comment by ckrause** [comment]
How many programs can we expect to benefit from this operation? More than a hundred?

**Comment by neoneye** [comment]
548 places that can be replaced by a `zap` instruction.

I did a grep for this regex `lpb [$]\d+\n\s*dif [$]\d+,[$]?\d+\n\s*lpe`

**Comment by ckrause** [comment]
A comparison with other operations is shown below. Except for `clr` (which we should remove), the others have thousands of places of usage. Note sure if we should add it.

```csv
mov,317375
add,255416
sub,139997
trn,10957
mul,119927
div,62167
dif,6494
mod,16930
pow,36550
gcd,8419
bin,17577
cmp,19512
min,2942
max,12686
lpb,80448
lpe,80448
clr,26
seq,52467
```

**Comment by neoneye** [comment]
Let's ignore the `zap` instruction for now, we can always resurrect it.
