### ISSUE TITLE
Minimization hanging

### ISSUE THREAD

**Issue by neoneye** [loda-lang/loda-cpp#206]
Trying to minimize an already existing program, then it seems to be hanging forever.

Example: 
https://loda-lang.org/edit/?oeis=A018000

Navigate to the dir containing the program.

```
PROMPT> pwd
/Users/homedir/loda/programs/oeis/018
PROMPT> loda minimize A018000
[takes a long time without anything happening, after 30s I kill it]
^C
PROMPT>
```

If I make changes the to the program, and run `loda minimize A018000`, then it completes immediately.

**Comment by kotenok2000** [comment]
It ran for 4:55.55 minutes for me and returned identical program.

**Comment by ckrause** [comment]
Minimization is an expensive operation. A fast alternative is `optimize`, but that is way less efficient. For `minimize`, using `-t` for reducing the number of terms to be checked should help to improve the performance. But strangely, even `loda minimize -t 10 A018000` takes about 4 mins on my laptop. This needs investigation...

**Comment by ckrause** [comment]
I fixed it here: https://github.com/loda-lang/loda-cpp/commit/ac15fe81b98a99fb671790ab734b229034bf4044 , but be careful: the default number of terms for minimize changed from 100 to 10. The command may be too aggressive now with the default setting! You can change it using `-t` now. One option would be:

1. Run `minimize -t 100` as default;
2. If it doesn't terminate after 30s, kill it and restart with `-t 10`
