### ISSUE TITLE
`seq` and negative input

### ISSUE THREAD

**Issue by neoneye** [loda-lang/loda-cpp#210]
In `~/.loda-rust/analytics/programs_invalid_verbose.csv` there are the programs that is causing trouble and what seems to be the cause. It's been 3 months since I last looked at it and I don't recall seeing this problem. Now there are 90 invalid programs with `EvalSequenceWithNegativeParameter`. Probably recently introduced.

# Problem

The webeditor can't execute the [A004001](https://loda-lang.org/edit/?oeis=A004001) program, since the input is negative in first iteration.

```asm
lpb $0
  sub $0,1
  mov $2,$0
  seq $2,93879 ; First differences of A004001.
  add $1,$2
lpe
add $1,1
mov $0,$1
```

[git history for A004001.asm](https://github.com/loda-lang/loda-programs/blob/main/oeis/004/A004001.asm): The file was added to git 5 days ago.

# Solution A

LODA-CPP rejecting negative input, before accepting a new program / update to existing program.

# Solution B

There are 90 programs that uses negative inputs when computing the 1st term. These will have to be deleted manually (a long list).

```
A004001
A006454
A006998 calls A205591 which uses negative input
A007000
A007417
A024450
A024924
A025475
A048148
A049628
A051293
A066077
A069891
A072004
A072114
A075994
A076793
A080358
A080677
A080704
A084505
A086052
A086525
A092401
A097332
A099958
A103116
A108906
A112073
A112556
A113510
A116466
A117276
A127719
A131118
A131804
A135339
A141253
A157100
A159793
A159795
A160118
A160119
A160428
A160744
A161426
A161832
A164158
A167549
A168472
A171645
A172243
A180016
A182716
A182843
A188557
A193215
A205591
A211634
A211637
A211638
A211646
A217069
A224914
A227844
A229506
A245380
A249435
A252749
A266532
A268395
A268672
A268708
A268905
A270593
A273324
A273780
A273781
A275112
A278491
A278603
A279557
A279927
A282282
A285985
A289898
A326118
A336415
A356005
```

**Comment by ckrause** [comment]
This is a bug in loda-cpp caused by enabling IE in checks. Needs to be fixed there

**Comment by ckrause** [comment]
Already fixed
