### ISSUE TITLE
Check command - print out match count

### ISSUE THREAD

**Issue by neoneye** [loda-lang/loda-cpp#30]
Sometimes I think I have crafted a new program that corresponds to an OEIS sequence.

I can manually see that the first 60 terms is a match. However I'm not sure how many terms match. Is it 800 terms until the first mismatch, or is it the 61 term.

I think I have used `-l debug` in the past, but it seems to output the same.

```
PROMPT> loda check A123456
error
PROMPT> loda check A123456 -l debug
error
PROMPT> 
```

Perhaps a message like this:

```
PROMPT> loda check A123456
error, 61 matching terms followed by a mismatch.
PROMPT> 
```

**Comment by ckrause** [comment]
You can use `loda check A123456 -b 1` => this prints it out in b-file format and reports where the first mismatch is.

When you have found a correct new program, you can also try `loda mine test.asm` to generate "similar" programs and check if it finds a match. It basically mutates the constants in the program and tries to find new matches. But note that it will at some point switch to normal mining (it won't stop).
