### ISSUE TITLE
Setup already on latest version

### ISSUE THREAD

**Issue by jonmaiga** [loda-lang/loda-cpp#76]
I forgot I could just run loda setup and curled home the latest first.

```
===== Welcome to LODA v21.12.1! =====

This command will guide you through its setup.

Enter the directory where LODA should store its files.
Note that non-default locations require manually adding
the LODA_HOME environment variable to your computer.
Press return for the default location (see below).
[C:\Users\Jon Maiga\loda]

LODA v21.12.1 is available!
Do you want to install the update? (Y/n) Y
curl: (22) The requested URL returned error: 404 Not Found
2021-12-02 13:38:46|ERROR|Error fetching https://github.com/loda-lang/loda-cpp/releases/download/v21.12.1/loda-windows-19.exe
```
Perhaps it should check if we already  downloaded (this is maybe not only for Windows).

**Comment by ckrause** [comment]
I believe the issue is: the windows executable in the current release is called `loda-windows-19`, but it should be `loda-windows-19.exe`:

https://github.com/loda-lang/loda-cpp/releases/tag/v21.12.1

I will update the release pipeline to generate the correct filename.

**Comment by ckrause** [comment]
Done. I also updated the filename in the v21.12.1 release.
